# sennio.de website deployment

image: node:18

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - node
          script:
            - npm install
            # - npm test
      - step:
          name: Code linting
          script:
            - npm install eslint
            - npx eslint .
          caches:
            - node
  branches:
    master:
      - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install
              # - npm test
              - npm run-script build
              - mkdir packaged
              - tar -czvf packaged/package-${BITBUCKET_BUILD_NUMBER}.tar.gz -C build .
            artifacts:
              - packaged/**
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
          name: Deploy to sennio.de
          trigger: manual
          deployment: Production
          clone:
            enabled: false
          script:
            - mkdir upload
            - tar -xf packaged/package-${BITBUCKET_BUILD_NUMBER}.tar.gz -C upload
            - pipe: atlassian/ftp-deploy:0.5.0
              variables:
                USER: $FTP_USER
                PASSWORD: $FTP_PASSWORD
                SERVER: $SERVER_HOST
                REMOTE_PATH: '/website'
                LOCAL_PATH: 'upload'
                DELETE_FLAG: 'false'
                # DEBUG: '<boolean>' # Optional
                # SET_ARGS: '<string>' # Optional.
                # EXTRA_ARGS: '<string>' # Optional.
