name: 🚀 Deploy website on push

on:
  push:
    branches: ["master"]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./build/"
          server-dir: "/"
